<?php

/* custom routes generated by CRUD */

Route::group(array('prefix' => 'admin'), function () {
	Route::resource('orders', 'OrdersController');
	Route::get('orders/{id}/delete', array('as' => 'admin.orders.delete', 'uses' => 'OrdersController@getDelete'));
	Route::get('orders/{id}/confirm-delete', array('as' => 'admin.orders.confirm-delete', 'uses' => 'OrdersController@getModalDelete'));
});

